### PR TITLE
feat: add pkg/erofs

### PR DESCRIPTION
**Pull request by myml**
add erofs package

### CODE REVIEW

**Comment by myml** [comment]
@nicocha30

**Comment by nicocha30** [comment]
@myml
Can you tell me a little bit more? Why erofs is necessary?

**Comment by myml** [comment]
I need read EROFS image using golang.

pkg/erofs is a newly added package in gvisor.  This is the only go library I have found so far that can read EROFS image file.

**Comment by nicocha30** [comment]
This repo hosts a modified version of gvisor for Ligolo-ng.
As the erofs package is not used by Ligolo-ng, I don't understand why this PR is necessary.

**Comment by myml** [comment]
Okay. I thought this repository was meant to be a 'prune golang' version of gvisor.

**Comment by nicocha30** [comment]
@myml use the "go" branch of the official gvisor repository 😉

**Pull request closed without merging**
